[project]
name = "pugixml-cython"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matthew Reid", email = "matt@nomadic-recording.com" }
]
requires-python = ">=3.10"
license = "MIT"
dependencies = []

[build-system]
requires = [
    "setuptools>=61",
    "numpy",
    "cython>=3.3.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests", "tests.*"]

[tool.setuptools.package-data]
pugixml_cython = [
    "*.pyx",
    "*.pxd",
    "extern/pugixml/src/pugixml.cpp",
    "extern/pugixml/src/pugixml.hpp",
    "extern/pugixml/src/pugiconfig.hpp",
]

[dependency-groups]
build = [
    "cython>=3.3.0",
    "setuptools>=84.0.0",
]
dev = [
    {include-group = "build"},
    {include-group = "test"}
]
test = [
    "pytest>=9.1.1",
]
