import enum
from collections.abc import Iterator
from typing import Self

class NodeType(enum.IntEnum):
    NODE_NULL = ...
    NODE_ELEMENT = ...
    NODE_PCData = ...
    NODE_CDATA = ...
    NODE_COMMENT = ...
    NODE_PI = ...
    NODE_DECLARATION = ...
    NODE_DOCTYPE = ...


class Document:
    def add_node_type_exclusion(self, node_type: NodeType) -> None: ...
    def set_node_type_exclusions(self, node_types: list[NodeType]) -> None: ...
    def load_string(self, xml_string: str) -> None: ...
    def clear(self) -> None: ...
    @property
    def has_document(self) -> bool: ...
    @property
    def has_root(self) -> bool: ...
    def get_root(self) -> Element | None: ...
    def xpath_find(self, xpath: str) -> Element | None: ...
    def xpath_findall(self, xpath: str) -> list[Element]: ...


class Element:
    @property
    def type(self) -> NodeType: ...
    @property
    def parent(self) -> Self | None: ...
    @property
    def root(self) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def text(self) -> str | None: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def is_null(self) -> bool: ...
    @property
    def has_text(self) -> bool: ...
    @property
    def hash_value(self) -> int: ...
    @property
    def attributes(self) -> dict[str, str]: ...
    @property
    def node_position(self) -> tuple[int, ...]: ...
    def find_from_position(self, position: tuple[int, ...]) -> Self | None: ...
    def walk(self) -> Iterator[Self]: ...
    def __iter__(self) -> Iterator[Self]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Self: ...
